// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import ag_solanago "github.com/gagliardetto/solana-go"

var Addresses = map[string]ag_solanago.PublicKey{
	"11111111111111111111111111111111":             ag_solanago.MustPublicKeyFromBase58("11111111111111111111111111111111"),
	"6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P":  ag_solanago.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"),
	"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL": ag_solanago.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
	"Ce6TQqeHC9p8KetsN6JsjHK7UTZk7nasjjnr7XxXp9F1": ag_solanago.MustPublicKeyFromBase58("Ce6TQqeHC9p8KetsN6JsjHK7UTZk7nasjjnr7XxXp9F1"),
	"SysvarRent111111111111111111111111111111111":  ag_solanago.MustPublicKeyFromBase58("SysvarRent111111111111111111111111111111111"),
	"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA":  ag_solanago.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
	"metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s":  ag_solanago.MustPublicKeyFromBase58("metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"),
}
