// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package pump

import (
	"encoding/json"
	"errors"
	"fmt"
	ag_jsonrpc "github.com/gagliardetto/solana-go/rpc/jsonrpc"
)

var (
	_ *json.Encoder        = nil
	_ *ag_jsonrpc.RPCError = nil
	_ fmt.Formatter        = nil
	_                      = errors.ErrUnsupported
)
var (
	ErrNotAuthorized = &customErrorDef{
		code: 6000,
		msg:  "The given account is not authorized to execute this instruction.",
		name: "NotAuthorized",
	}
	ErrAlreadyInitialized = &customErrorDef{
		code: 6001,
		msg:  "The program is already initialized.",
		name: "AlreadyInitialized",
	}
	ErrTooMuchSolRequired = &customErrorDef{
		code: 6002,
		msg:  "slippage: Too much SOL required to buy the given amount of tokens.",
		name: "TooMuchSolRequired",
	}
	ErrTooLittleSolReceived = &customErrorDef{
		code: 6003,
		msg:  "slippage: Too little SOL received to sell the given amount of tokens.",
		name: "TooLittleSolReceived",
	}
	ErrMintDoesNotMatchBondingCurve = &customErrorDef{
		code: 6004,
		msg:  "The mint does not match the bonding curve.",
		name: "MintDoesNotMatchBondingCurve",
	}
	ErrBondingCurveComplete = &customErrorDef{
		code: 6005,
		msg:  "The bonding curve has completed and liquidity migrated to raydium.",
		name: "BondingCurveComplete",
	}
	ErrBondingCurveNotComplete = &customErrorDef{
		code: 6006,
		msg:  "The bonding curve has not completed.",
		name: "BondingCurveNotComplete",
	}
	ErrNotInitialized = &customErrorDef{
		code: 6007,
		msg:  "The program is not initialized.",
		name: "NotInitialized",
	}
	ErrWithdrawTooFrequent = &customErrorDef{
		code: 6008,
		msg:  "Withdraw too frequent",
		name: "WithdrawTooFrequent",
	}
	Errors = map[int]CustomError{
		6000: ErrNotAuthorized,
		6001: ErrAlreadyInitialized,
		6002: ErrTooMuchSolRequired,
		6003: ErrTooLittleSolReceived,
		6004: ErrMintDoesNotMatchBondingCurve,
		6005: ErrBondingCurveComplete,
		6006: ErrBondingCurveNotComplete,
		6007: ErrNotInitialized,
		6008: ErrWithdrawTooFrequent,
	}
)

type CustomError interface {
	Code() int
	Name() string
	Error() string
}

type customErrorDef struct {
	code int
	name string
	msg  string
}

func (e *customErrorDef) Code() int {
	return e.code
}

func (e *customErrorDef) Name() string {
	return e.name
}

func (e *customErrorDef) Error() string {
	return fmt.Sprintf("%s(%d): %s", e.name, e.code, e.msg)
}

func DecodeCustomError(rpcErr error) (err error, ok bool) {
	if errCode, o := decodeErrorCode(rpcErr); o {
		if customErr, o := Errors[errCode]; o {
			err = customErr
			ok = true
			return
		}
	}
	return
}

func decodeErrorCode(rpcErr error) (errorCode int, ok bool) {
	var jErr *ag_jsonrpc.RPCError
	if errors.As(rpcErr, &jErr) && jErr.Data != nil {
		if root, o := jErr.Data.(map[string]interface{}); o {
			if rootErr, o := root["err"].(map[string]interface{}); o {
				if rootErrInstructionError, o := rootErr["InstructionError"]; o {
					if rootErrInstructionErrorItems, o := rootErrInstructionError.([]interface{}); o {
						if len(rootErrInstructionErrorItems) == 2 {
							if v, o := rootErrInstructionErrorItems[1].(map[string]interface{}); o {
								if v2, o := v["Custom"].(json.Number); o {
									if code, err := v2.Int64(); err == nil {
										ok = true
										errorCode = int(code)
									}
								} else if v2, o := v["Custom"].(float64); o {
									ok = true
									errorCode = int(v2)
								}
							}
						}
					}
				}
			}
		}
	}
	return
}
